apiVersion: v1
entries:
  helm-dashboard:
  - apiVersion: v2
    appVersion: 1.3.3
    created: "2024-08-23T17:08:51.402501+02:00"
    description: A GUI Dashboard for Helm by Komodor customized by me
    digest: 34739d66e9f899570c340d08b2dc579ac5e3bec72a85a8cfc08cdb90dacc0207
    icon: https://raw.githubusercontent.com/komodorio/helm-dashboard/main/images/logo.svg
    name: helm-dashboard
    type: application
    urls:
    - https://franzudev.github.com/helm-dashboard/helm-dashboard-2.0.1.tgz
    version: 2.0.1
generated: "2024-08-23T17:08:51.401862+02:00"
